require(tidyr)
require(dplyr)
require(stringr)
require(lubridate)
require(feather)
require(ggplot2)
require(sp)
require(rgeos)
require(rgdal)
require(sf)

require(shiny)
require(leaflet)
require(shinyBS)
require(shinyjs)
require(parallel)
#library('geosphere')